### ISSUE TITLE
Publish avrodoc to gh-pages

### ISSUE THREAD

**Issue by OneCricketeer** [zolyfarkas/avro-schema-examples#1]
Rather than linking to a JAR, I feel the information would be more consumable if hosted on a static site like Github Pages.

**Comment by zolyfarkas** [comment]
Implemented in:

```
  <parent>
    <groupId>org.spf4j.avro</groupId>
    <artifactId>schema-parent-pom</artifactId>
    <version>0.16</version>
  </parent>
```

for an example see: https://github.com/zolyfarkas/fred-schema 
and the avrodoc at: https://zolyfarkas.github.io/fred-schema

**Comment by OneCricketeer** [comment]
LGTM 👍
